import { readFileSync, writeFileSync } from "node:fs";

function safeJson(value) {
  return JSON.stringify(value).replace(/</g, "\\u003c");
}

export function renderReplay(recording) {
  const data = safeJson(recording);
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${recording.title || "Herdr Replay"}</title><style>
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui;background:#0b0f0d;color:#e6ece8}*{box-sizing:border-box}body{margin:0}.bar{height:58px;display:flex;align-items:center;justify-content:space-between;padding:0 22px;border-bottom:1px solid #29332d;background:#121814}.brand{font-weight:700}.muted{color:#8e9b93}.layout{display:grid;grid-template-columns:minmax(0,1.5fr) 360px;min-height:calc(100vh - 126px)}main{padding:18px}.terminal{background:#050806;border:1px solid #29332d;border-radius:8px;min-height:340px;overflow:hidden}.terminal header{padding:10px 13px;border-bottom:1px solid #29332d;color:#9eaaa2}.terminal pre{margin:0;padding:15px;white-space:pre-wrap;font:13px/1.55 ui-monospace,SFMono-Regular,monospace}.side{border-left:1px solid #29332d;padding:18px;background:#0e1310}.event{padding:12px 0;border-bottom:1px solid #202923}.time{font:12px ui-monospace,monospace;color:#86d49f}.lanes{margin-top:18px}.lane{display:grid;grid-template-columns:90px 1fr;gap:10px;align-items:center;margin:10px 0}.track{height:18px;background:#222b26;border-radius:4px;position:relative;overflow:hidden}.mark{position:absolute;top:0;bottom:0;background:#55b879}.mark.blocked{background:#d3904f}.mark.done{background:#648fd1}.cursor{position:absolute;top:0;bottom:0;width:2px;background:#fff}.controls{height:68px;padding:12px 18px;border-top:1px solid #29332d;display:grid;grid-template-columns:auto 1fr auto;gap:14px;align-items:center;background:#121814}button{background:#e6ece8;color:#0b0f0d;border:0;border-radius:6px;padding:8px 14px;font:inherit}input{width:100%;accent-color:#55b879}@media(max-width:760px){.layout{grid-template-columns:1fr}.side{border-left:0;border-top:1px solid #29332d}}
</style></head><body><div class="bar"><div class="brand">herdr replay / ${recording.title || "session"}</div><div class="muted" id="meta"></div></div><div class="layout"><main><section class="terminal"><header id="pane">No event selected</header><pre id="output">Move the timeline to replay this session.</pre></section><div class="lanes" id="lanes"></div></main><aside class="side"><h3>At this moment</h3><div id="events"></div></aside></div><div class="controls"><button id="play">Play</button><input id="slider" type="range" min="0" max="1000" value="0" aria-label="Replay position"><span id="clock">00:00</span></div><script>
const recording=${data};const start=Date.parse(recording.startedAt),end=Date.parse(recording.endedAt||recording.updatedAt||recording.startedAt),duration=Math.max(1,end-start);const slider=document.querySelector('#slider'),output=document.querySelector('#output'),pane=document.querySelector('#pane'),eventsEl=document.querySelector('#events'),clock=document.querySelector('#clock'),play=document.querySelector('#play');document.querySelector('#meta').textContent=(recording.agents||[]).length+' agents · '+recording.events.length+' events';let timer;function fmt(ms){const s=Math.floor(ms/1000);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}function render(){const point=start+duration*(+slider.value/1000),visible=recording.events.filter(e=>Date.parse(e.at)<=point),recent=visible.slice(-5),terminal=[...visible].reverse().find(e=>e.type==='terminal.snapshot');const current=[...visible].reverse().find(e=>e.agent);pane.textContent=current?(current.agent+' · '+(current.status||current.type)):'Session starting';output.textContent=terminal?terminal.text:'No terminal evidence at this point.';eventsEl.innerHTML=recent.map(e=>'<div class="event"><div class="time">'+fmt(Date.parse(e.at)-start)+'</div><div>'+e.type.replace('.', ' → ')+' '+(e.agent||'')+'</div></div>').join('');clock.textContent=fmt(point-start)+' / '+fmt(duration);document.querySelectorAll('.cursor').forEach(c=>c.style.left=(+slider.value/10)+'%')}slider.oninput=render;play.onclick=()=>{if(timer){clearInterval(timer);timer=null;play.textContent='Play';return}play.textContent='Pause';timer=setInterval(()=>{slider.value=+slider.value>=1000?0:+slider.value+5;render()},60)};const byPane={};for(const e of recording.events){if(e.paneId)(byPane[e.paneId]??=[]).push(e)}document.querySelector('#lanes').innerHTML=Object.entries(byPane).map(([id,es])=>'<div class="lane"><span>'+id+'</span><div class="track">'+es.filter(e=>e.type==='agent.state'||e.type==='agent.discovered').map(e=>{const l=(Date.parse(e.at)-start)/duration*100;return '<span class="mark '+(e.status||'')+'" style="left:'+l+'%;width:8%"></span>'}).join('')+'<span class="cursor" style="left:0"></span></div></div>').join('');render();
</script></body></html>`;
}

export function exportReplay(inputPath, outputPath) {
  const recording = JSON.parse(readFileSync(inputPath, "utf8"));
  writeFileSync(outputPath, renderReplay(recording), "utf8");
}
